default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sales
  password: Gsl_Sales
  host: localhost

development:
  <<: *default
  database: sales_crm_development

production:
  <<: *default
  database: sales_crm_production
  username: sales_crm
  password: <%= ENV['SALES_CRM_DATABASE_PASSWORD'] %>
